export const SUBMIT_CONTACT_FORM = "SUBMIT_CONTACT_FORM";
export const SUBMIT_CONTACT_FORM_SUCCESS = "SUBMIT_CONTACT_FORM_SUCCESS";
export const SUBMIT_CONTACT_FORM_FAIL = "SUBMIT_CONTACT_FORM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";