
export const SUBMIT_ML_IMAGE = "SUBMIT_ML_IMAGE";
export const SUBMIT_ML_IMAGE_SUCCESS = "SUBMIT_ML_IMAGE_SUCCESS";
export const SUBMIT_ML_IMAGE_FAIL = "SUBMIT_ML_IMAGE_FAIL";


export const CROP_PREDICTION = "CROP_PREDICTION";
export const CROP_PREDICTION_SUCCESS = "CROP_PREDICTION_SUCCESS";
export const CROP_PREDICTION_FAIL = "CROP_PREDICTION_FAIL";

export const FERTILIZER_RECOMMENDATION = "FERTILIZER_RECOMMENDATION";
export const FERTILIZER_RECOMMENDATION_SUCCESS = "FERTILIZER_RECOMMENDATION_SUCCESS";
export const FERTILIZER_RECOMMENDATION_FAIL = "FERTILIZER_RECOMMENDATION_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";